/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionBD.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User-Hp
 */
public class VentanaCambios extends javax.swing.JFrame {
    private Conexion conexion;

    /**
     * Creates new form VentanaCambios
     */
    public VentanaCambios() {
        initComponents();
           conexion = Conexion.getInstancia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btm_Modificar = new javax.swing.JButton();
        btm_salir = new javax.swing.JButton();
        btm_marca = new javax.swing.JLabel();
        btm_idModelo = new javax.swing.JLabel();
        btm_idCalcomania = new javax.swing.JLabel();
        btm_fechafab = new javax.swing.JLabel();
        btm_precio = new javax.swing.JLabel();
        Marca_idMarca = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        idAutomovil = new javax.swing.JTextField();
        fecha_fabricacion = new javax.swing.JTextField();
        precio_lista = new javax.swing.JTextField();
        btm_placa = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        btm_Cliente = new javax.swing.JLabel();
        Cliente_idCliente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Contenido1 = new javax.swing.JTable();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btm_Modificar.setText("MODIFICAR");
        btm_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_ModificarActionPerformed(evt);
            }
        });

        btm_salir.setText("SALIR");
        btm_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_salirActionPerformed(evt);
            }
        });

        btm_marca.setText("MARCA");

        btm_idModelo.setText("MODELO");

        btm_idCalcomania.setText("IDAUTOMOVIL");

        btm_fechafab.setText("FECHA FABRICACION");

        btm_precio.setText("PRECIO");

        Marca_idMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Marca_idMarcaActionPerformed(evt);
            }
        });

        idAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAutomovilActionPerformed(evt);
            }
        });

        btm_placa.setText("PLACA");

        btm_Cliente.setText("CLIENTE");

        Cliente_idCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C001", "C002", "C003", "C004", "C005", "C006", "C007" }));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\406746_car_icon.png")); // NOI18N

        tabla_Contenido1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            }
        ));
        jScrollPane2.setViewportView(tabla_Contenido1);

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btm_idCalcomania)
                                        .addComponent(btm_idModelo)
                                        .addComponent(btm_precio))
                                    .addGap(53, 53, 53))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btm_fechafab)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btm_placa)
                                    .addComponent(btm_Cliente)
                                    .addComponent(btm_marca))
                                .addGap(87, 87, 87)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Marca_idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btm_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btm_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm_idCalcomania)
                            .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm_idModelo))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm_precio)
                            .addComponent(precio_lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btm_fechafab)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btm_Cliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Cliente_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm_placa)
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm_marca)
                            .addComponent(Marca_idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_ModificarActionPerformed
        // TODO add your handling code here:

        String idAutomovilText = idAutomovil.getText();
        String modeloText = modelo.getText();
        String precioText = precio_lista.getText();
        String fechaText = fecha_fabricacion.getText();
        String clienteIdString = Cliente_idCliente.getSelectedItem().toString();
        String placaText = placa.getText();
        String marcaIdText = Marca_idMarca.getText();

        // Que los campos no estén vacíos
        if (idAutomovilText.isEmpty() || modeloText.isEmpty() || precioText.isEmpty() || fechaText.isEmpty() || clienteIdString.isEmpty() || placaText.isEmpty() || marcaIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validar el formato de la fecha (yyyy-MM-dd)
        if (!fechaText.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Utilice yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Precio contenga solo números
        if (!precioText.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El precio debe contener solo números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que el ID no esté repetido
        String consultaIdRepetido = "SELECT COUNT(*) FROM Automovil WHERE idAutomovil = ? AND idAutomovil <> ?";
        int cantidadRegistros = 0;  
        if (cantidadRegistros > 0) {
            JOptionPane.showMessageDialog(this, "El ID ya existe. Ingrese un ID diferente", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar el formato de la placa
        if (!placaText.matches("[A-Z]{3}\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de placa no válida. Debe ser tres letras seguidas de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que la placa no esté repetida
        String consultaPlacaRepetida = "SELECT COUNT(*) FROM Automovil WHERE placa = ?";
        int cantidadPlacasRepetidas = 0;  // Aquí debes realizar la consulta a la base de datos para obtener la cantidad de placas repetidas

        if (cantidadPlacasRepetidas > 0) {
            JOptionPane.showMessageDialog(this, "La placa ya está registrada. Ingrese una placa diferente", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validar el formato de la marca
        String marcaString = Marca_idMarca.getText();
        if (!marcaIdText.matches("[A-Za-z]\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de Marca no válido. Debe ser una letra seguida exactamente de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Consulta SQL para la actualización
        String consultaSQL = "UPDATE Automovil SET modelo = ?, precio_lista = ?, fecha_fabricacion = ?, cliente_idCliente = ?, placa = ?, Marca_idMarca = ? WHERE idAutomovil = ?";

        try {
            // Preparar la consulta
            PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);
            pstmt.setString(1, modeloText);
            pstmt.setString(2, precioText);
            pstmt.setString(3, fechaText);
            pstmt.setString(4, clienteIdString);
            pstmt.setString(5, placaText);
            pstmt.setString(6, marcaIdText);
            pstmt.setString(7, idAutomovilText);

            // Ejecutar la consulta de actualización
            int filasActualizadas = pstmt.executeUpdate();

            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el automóvil con ID: " + idAutomovilText, "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Cerrar el PreparedStatement
            pstmt.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la actualización: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btm_ModificarActionPerformed

    private void btm_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         VentanaPrincipal menu = new VentanaPrincipal();
         menu.setVisible(true);
    }//GEN-LAST:event_btm_salirActionPerformed

    private void Marca_idMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Marca_idMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Marca_idMarcaActionPerformed

    private void idAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAutomovilActionPerformed
        // TODO add your handling code here:
         String idAutomovilText = idAutomovil.getText();
    
    if (!idAutomovilText.matches("[A-Za-z]\\d{3}")) {
        JOptionPane.showMessageDialog(this, "Formato de ID de automóvil no válido. Debe ser una letra seguida de tres números", "Error", JOptionPane.ERROR_MESSAGE);
        idAutomovil.setText(""); 
    }
    }//GEN-LAST:event_idAutomovilActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:

        try {
            String consultaSQL = "SELECT * FROM Automovil";

            PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);
            ResultSet resultado = pstmt.executeQuery();

            DefaultTableModel modeloTabla = new DefaultTableModel();
            modeloTabla.setColumnIdentifiers(new String[]{
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            });

            while (resultado.next()) {
                Object[] fila = new Object[]{
                    resultado.getString("idAutomovil"),
                    resultado.getString("modelo"),
                    resultado.getString("precio_lista"),
                    resultado.getString("fecha_fabricacion"),
                    resultado.getString("cliente_idCliente"),
                    resultado.getString("placa"),
                    resultado.getString("Marca_idMarca")
                };
                modeloTabla.addRow(fila);
            }

            tabla_Contenido1.setModel(modeloTabla);

            pstmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al buscar automóviles: " + e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCambios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cliente_idCliente;
    private javax.swing.JTextField Marca_idMarca;
    private javax.swing.JLabel btm_Cliente;
    private javax.swing.JButton btm_Modificar;
    private javax.swing.JLabel btm_fechafab;
    private javax.swing.JLabel btm_idCalcomania;
    private javax.swing.JLabel btm_idModelo;
    private javax.swing.JLabel btm_marca;
    private javax.swing.JLabel btm_placa;
    private javax.swing.JLabel btm_precio;
    private javax.swing.JButton btm_salir;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField fecha_fabricacion;
    private javax.swing.JTextField idAutomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField precio_lista;
    private javax.swing.JTable tabla_Contenido1;
    // End of variables declaration//GEN-END:variables
}
