/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionBD.Conexion;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User-Hp
 */
public class VentanaConsultas extends javax.swing.JFrame {
    private Conexion conexion;

    /**
     * Creates new form VentanaConsultas
     */
    public VentanaConsultas() {
        initComponents();
           conexion = Conexion.getInstancia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btm_fecha = new javax.swing.JPanel();
        btm_idMarca = new javax.swing.JLabel();
        Marca_idMarca = new javax.swing.JTextField();
        btm_modelo = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        btm_idAutomovil = new javax.swing.JLabel();
        idAutomovil = new javax.swing.JTextField();
        btm_fechaConsultas = new javax.swing.JLabel();
        fecha_fabricacion = new javax.swing.JTextField();
        btm_Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Contenido = new javax.swing.JTable();
        placa = new javax.swing.JTextField();
        btm_Placa = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btm_fecha.setBackground(new java.awt.Color(129, 191, 241));

        btm_idMarca.setText("IDMARCA");

        btm_modelo.setText("MODELO");

        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });

        btm_idAutomovil.setText("IDAUTOMOVIL");

        btm_fechaConsultas.setText("FECHA");

        btm_Salir.setText("SALIR");
        btm_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_SalirActionPerformed(evt);
            }
        });

        tabla_Contenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            }
        ));
        jScrollPane1.setViewportView(tabla_Contenido);

        btm_Placa.setText("PLACA");

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\2541673_find_look_magnifying glass_search_icon.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\748995_back to the future_car_delorean_future_transport_icon.png")); // NOI18N

        javax.swing.GroupLayout btm_fechaLayout = new javax.swing.GroupLayout(btm_fecha);
        btm_fecha.setLayout(btm_fechaLayout);
        btm_fechaLayout.setHorizontalGroup(
            btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btm_fechaLayout.createSequentialGroup()
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btm_fechaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btm_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btm_fechaLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(btm_fechaLayout.createSequentialGroup()
                                    .addComponent(btm_idAutomovil)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btm_fechaLayout.createSequentialGroup()
                                    .addComponent(btm_modelo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btm_fechaLayout.createSequentialGroup()
                                    .addComponent(btm_fechaConsultas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fecha_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btm_fechaLayout.createSequentialGroup()
                                    .addComponent(btm_Placa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btm_fechaLayout.createSequentialGroup()
                                    .addComponent(btm_idMarca)
                                    .addGap(56, 56, 56)
                                    .addComponent(Marca_idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(btm_fechaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(btm_fechaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btm_fechaLayout.setVerticalGroup(
            btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btm_fechaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_idAutomovil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_modelo)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_fechaConsultas)
                    .addComponent(fecha_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_Placa))
                .addGap(18, 18, 18)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca_idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_idMarca))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btm_fechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btm_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btm_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloActionPerformed

    private void btm_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VentanaPrincipal menu = new VentanaPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_btm_SalirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    try {
        conexion.iniciarTransaccion();

        String idAutomovilText = idAutomovil.getText();
        String modeloText = modelo.getText();
        String fechaText = fecha_fabricacion.getText();
        String placaText = placa.getText();
        String idMarcaText = Marca_idMarca.getText();

        String consultaSQL = "SELECT * FROM Automovil WHERE 1=1";

        if (!idAutomovilText.isEmpty()) {
            consultaSQL += " AND idAutomovil = ?";
        }

        if (!modeloText.isEmpty()) {
            consultaSQL += " AND modelo = ?";
        }

        if (!fechaText.isEmpty()) {
            consultaSQL += " AND fecha_fabricacion = ?";
        }

        if (!placaText.isEmpty()) {
            consultaSQL += " AND placa = ?";
        }

        if (!idMarcaText.isEmpty()) {
            consultaSQL += " AND Marca_idMarca = ?";
        }

        try {
            PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);

            int paramIndex = 1;

            if (!idAutomovilText.isEmpty()) {
                pstmt.setString(paramIndex++, idAutomovilText);
            }

            if (!modeloText.isEmpty()) {
                pstmt.setString(paramIndex++, modeloText);
            }

            if (!fechaText.isEmpty()) {
                pstmt.setString(paramIndex++, fechaText);
            }

            if (!placaText.isEmpty()) {
                pstmt.setString(paramIndex++, placaText);
            }

            if (!idMarcaText.isEmpty()) {
                pstmt.setString(paramIndex++, idMarcaText);
            }

            DefaultTableModel modeloTabla = (DefaultTableModel) tabla_Contenido.getModel();
            modeloTabla.setRowCount(0);

            ConsultaAutomovilThread thread = new ConsultaAutomovilThread(consultaSQL, pstmt, modeloTabla);
            thread.start();

            conexion.confirmarTransaccion();
        } catch (SQLException e) {
            try {
                conexion.revertirTransaccion();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al revertir la transacción: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error al revertir la transacción: " + ex.getMessage());
            }
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al realizar la búsqueda: " + e.getMessage());
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println("Error al realizar la búsqueda: " + e.getMessage());
    }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Marca_idMarca;
    private javax.swing.JLabel btm_Placa;
    private javax.swing.JButton btm_Salir;
    private javax.swing.JPanel btm_fecha;
    private javax.swing.JLabel btm_fechaConsultas;
    private javax.swing.JLabel btm_idAutomovil;
    private javax.swing.JLabel btm_idMarca;
    private javax.swing.JLabel btm_modelo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField fecha_fabricacion;
    private javax.swing.JTextField idAutomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField placa;
    private javax.swing.JTable tabla_Contenido;
    // End of variables declaration//GEN-END:variables
}
