/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import ConexionBD.Conexion;
import controlador.AutomovilDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User-Hp
 */
public class VentanaAltas extends javax.swing.JFrame {
        private Conexion conexion;
        private AutomovilDAO automovilDAO;
        



    /**
     * Creates new form AltaAuto
     */
    public VentanaAltas() {
        initComponents();
           conexion = Conexion.getInstancia();
                    automovilDAO = new AutomovilDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdAutomovil = new javax.swing.JLabel();
        idAutomovil = new javax.swing.JTextField();
        txtModelo = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JLabel();
        precio_lista = new javax.swing.JTextField();
        txtFechaFab = new javax.swing.JLabel();
        fecha_fabricacion = new javax.swing.JTextField();
        Cliente_idCliente = new javax.swing.JComboBox<>();
        txtCliente = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        Marca_idMarca = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Contenido1 = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuABCC = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        txtIdAutomovil.setText("IDAUTOMOVIL");

        idAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAutomovilActionPerformed(evt);
            }
        });

        txtModelo.setText("MODELO");

        txtPrecio.setText("PRECIO");

        precio_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_listaActionPerformed(evt);
            }
        });

        txtFechaFab.setText("FECHA FABRICACION");

        Cliente_idCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C001", "C002", "C003", "C004", "C005", "C006", "C007" }));
        Cliente_idCliente.setActionCommand("");
        Cliente_idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_idClienteActionPerformed(evt);
            }
        });

        txtCliente.setText("CLIENTE");

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        txtPlaca.setText("PLACA");

        txtMarca.setText("MARCA");

        Marca_idMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Marca_idMarcaActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\2526582_transportation_vehicle_icon.png")); // NOI18N

        tabla_Contenido1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            }
        ));
        jScrollPane2.setViewportView(tabla_Contenido1);

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFab)
                            .addComponent(txtCliente)
                            .addComponent(txtPlaca)
                            .addComponent(txtMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_fabricacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(Marca_idMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio_lista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cliente_idCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(placa)))
                    .addComponent(txtIdAutomovil)
                    .addComponent(txtModelo)
                    .addComponent(txtPrecio))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdAutomovil)
                            .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio)
                            .addComponent(precio_lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaFab)
                            .addComponent(fecha_fabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cliente_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(12, 12, 12)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Marca_idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca)))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenuABCC.setText("ALTAS");
        jMenuBar1.add(jMenuABCC);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precio_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_listaActionPerformed

    private void Cliente_idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_idClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Cliente_idClienteActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void Marca_idMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Marca_idMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Marca_idMarcaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         VentanaPrincipal menu = new VentanaPrincipal();
         menu.setVisible(true);
      
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    String idAutomovilText = idAutomovil.getText();
    String modeloText = modelo.getText();
    String precioListaText = precio_lista.getText();
    String fechaFabricacionText = fecha_fabricacion.getText();
    String clienteIdString = Cliente_idCliente.getSelectedItem().toString(); 
    String placaText = placa.getText();
    String marcaIdText = Marca_idMarca.getText();

      if (idAutomovilText.isEmpty() || modeloText.isEmpty() || precioListaText.isEmpty() ||
            fechaFabricacionText.isEmpty() || clienteIdString.isEmpty() || placaText.isEmpty() || marcaIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!fechaFabricacionText.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Utilice yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!precioListaText.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El precio debe contener solo números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!placaText.matches("[A-Z]{3}\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de placa no válida. Debe ser tres letras seguidas de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String consultaPlacaRepetida = "SELECT COUNT(*) FROM Automovil WHERE placa = ?";
        int cantidadPlacasRepetidas = 0;  
        if (cantidadPlacasRepetidas > 0) {
            JOptionPane.showMessageDialog(this, "La placa ya está registrada. Ingrese una placa diferente", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         if (!idAutomovilText.matches("[A-Za-z]\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de ID de automóvil no válido. Debe ser una letra seguida de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            idAutomovil.setText(""); 
        }
    if (!idAutomovilText.matches("[A-Za-z]\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de ID de automóvil no válido. Debe ser una letra seguida de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            idAutomovil.setText(""); 
            return;
        }
         int cantidadIdRepetidos = automovilDAO.contarAutomovilesPorId(idAutomovilText);
        if (cantidadIdRepetidos > 0) {
            JOptionPane.showMessageDialog(this, "El ID ya está registrado. Ingrese un ID diferente", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
         String marcaString = Marca_idMarca.getText();
        if (!marcaIdText.matches("[A-Za-z]\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato de Marca no válido. Debe ser una letra seguida exactamente de tres números", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
           automovilDAO.agregarAutomovil(idAutomovilText, modeloText, Double.parseDouble(precioListaText), fechaFabricacionText, placaText, clienteIdString, marcaIdText);
      try {
        automovilDAO.agregarAutomovil(idAutomovilText, modeloText, Double.parseDouble(precioListaText), fechaFabricacionText, placaText, clienteIdString, marcaIdText);
        JOptionPane.showMessageDialog(this, "Registro agregado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar el registro: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println("Error al agregar el registro: " + e.getMessage());
    }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:

        try {
            String consultaSQL = "SELECT * FROM Automovil";

            PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);
            ResultSet resultado = pstmt.executeQuery();

            DefaultTableModel modeloTabla = new DefaultTableModel();
            modeloTabla.setColumnIdentifiers(new String[]{
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            });

            while (resultado.next()) {
                Object[] fila = new Object[]{
                    resultado.getString("idAutomovil"),
                    resultado.getString("modelo"),
                    resultado.getString("precio_lista"),
                    resultado.getString("fecha_fabricacion"),
                    resultado.getString("cliente_idCliente"),
                    resultado.getString("placa"),
                    resultado.getString("Marca_idMarca")
                };
                modeloTabla.addRow(fila);
            }

            tabla_Contenido1.setModel(modeloTabla);

            pstmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al buscar automóviles: " + e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void idAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAutomovilActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_idAutomovilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cliente_idCliente;
    private javax.swing.JTextField Marca_idMarca;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField fecha_fabricacion;
    private javax.swing.JTextField idAutomovil;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenuABCC;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField precio_lista;
    private javax.swing.JTable tabla_Contenido1;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtFechaFab;
    private javax.swing.JLabel txtIdAutomovil;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtPrecio;
    // End of variables declaration//GEN-END:variables
}
