/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionBD.Conexion;
import controlador.AutomovilDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User-Hp
 */
public class VentanaBajas extends javax.swing.JFrame {
    private Conexion conexion;
    private AutomovilDAO automovilDAO;

    /**
     * Creates new form VentanaBajas
     */
    public VentanaBajas() {
        initComponents();
           conexion = Conexion.getInstancia();
        automovilDAO = new AutomovilDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmPanel1 = new javax.swing.JPanel();
        btmSalir = new javax.swing.JButton();
        btmPlaca = new javax.swing.JLabel();
        btmidAutomovil = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        idAutomovil = new javax.swing.JTextField();
        btm_Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Contenido = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        btnRespaldo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btmSalir.setBackground(new java.awt.Color(204, 204, 204));
        btmSalir.setText("SALIR");
        btmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalirActionPerformed(evt);
            }
        });

        btmPlaca.setText("PLACA");

        btmidAutomovil.setText("IDAUTOMOVIL");

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        idAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAutomovilActionPerformed(evt);
            }
        });

        btm_Eliminar.setText("ELIMINAR");
        btm_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_EliminarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\3668862_car_drive_service_icon.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User-Hp\\Downloads\\9004743_trash_delete_bin_remove_icon.png")); // NOI18N

        tabla_Contenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            }
        ));
        jScrollPane1.setViewportView(tabla_Contenido);

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        btnRespaldo.setText("RESPALDO");
        btnRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btmPanel1Layout = new javax.swing.GroupLayout(btmPanel1);
        btmPanel1.setLayout(btmPanel1Layout);
        btmPanel1Layout.setHorizontalGroup(
            btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btmPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(btmPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btmPanel1Layout.createSequentialGroup()
                        .addComponent(btmidAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btmPanel1Layout.createSequentialGroup()
                        .addComponent(btmPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btmPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(btmPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btm_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRespaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btmSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        btmPanel1Layout.setVerticalGroup(
            btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btmPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmidAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btmSalir)
                    .addGroup(btmPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btm_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar)
                        .addComponent(btnRespaldo)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         VentanaPrincipal menu = new VentanaPrincipal();
         menu.setVisible(true);
      
    }//GEN-LAST:event_btmSalirActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_placaActionPerformed

    private void btm_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_EliminarActionPerformed
        // TODO add your handling code here:
 String idAutomovilText = idAutomovil.getText();
    String placaText = placa.getText();

    if (idAutomovilText.isEmpty() && placaText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar el ID o la placa del automóvil para eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!idAutomovilText.isEmpty()) {
        automovilDAO.eliminarAutomovil(idAutomovilText);
    } else {
        automovilDAO.eliminarAutomovil(placaText);
    }
         try {
        if (!idAutomovilText.isEmpty()) {
            automovilDAO.eliminarAutomovil(idAutomovilText);
        } else {
            automovilDAO.eliminarAutomovil(placaText);
        }
        JOptionPane.showMessageDialog(this, "Automóvil eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el automóvil: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btm_EliminarActionPerformed

    private void idAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAutomovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAutomovilActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:

        try {
            String consultaSQL = "SELECT * FROM Automovil";

            PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);
            ResultSet resultado = pstmt.executeQuery();

            DefaultTableModel modeloTabla = new DefaultTableModel();
            modeloTabla.setColumnIdentifiers(new String[]{
                "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
            });

            while (resultado.next()) {
                Object[] fila = new Object[]{
                    resultado.getString("idAutomovil"),
                    resultado.getString("modelo"),
                    resultado.getString("precio_lista"),
                    resultado.getString("fecha_fabricacion"),
                    resultado.getString("cliente_idCliente"),
                    resultado.getString("placa"),
                    resultado.getString("Marca_idMarca")
                };
                modeloTabla.addRow(fila);
            }

            tabla_Contenido.setModel(modeloTabla);

            pstmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al buscar automóviles: " + e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void btnRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldoActionPerformed
        // TODO add your handling code here:
    try {
        String consultaSQL = "SELECT * FROM respaldo";

        PreparedStatement pstmt = conexion.getConexion().prepareStatement(consultaSQL);
        ResultSet resultado = pstmt.executeQuery();

        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.setColumnIdentifiers(new String[]{
            "idAutomovil", "modelo", "precio_lista", "fecha_fabricacion", "cliente_idCliente", "placa", "Marca_idMarca"
        });

        while (resultado.next()) {
            Object[] fila = new Object[]{
                resultado.getString("idAutomovil"),
                resultado.getString("modelo"),
                resultado.getString("precio_lista"),
                resultado.getString("fecha_fabricacion"),
                resultado.getString("cliente_idCliente"),
                resultado.getString("placa"),
                resultado.getString("Marca_idMarca")
            };
            modeloTabla.addRow(fila);
        }

        tabla_Contenido.setModel(modeloTabla);

        pstmt.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los datos de respaldo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println("Error al cargar los datos de respaldo: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRespaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btmPanel1;
    private javax.swing.JLabel btmPlaca;
    private javax.swing.JButton btmSalir;
    private javax.swing.JButton btm_Eliminar;
    private javax.swing.JLabel btmidAutomovil;
    private javax.swing.JButton btnRespaldo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField idAutomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField placa;
    private javax.swing.JTable tabla_Contenido;
    // End of variables declaration//GEN-END:variables
}
